### ISSUE TITLE
[Bug] You're Right flips embed images

### ISSUE THREAD

**Issue by wont-stream** [SpikeHD/shelter-plugins#39]
**Describe the bug**
The images inside of embeds are flipped

**To Reproduce**
- Send a link with an embed, ex https://github.com/uwu/shelter 

**Expected behavior**
Doesn't flip the image

**Screenshots**
![{C7D4BEF3-BC67-432C-9258-1C7DE6C28327}](https://github.com/user-attachments/assets/98e3a92b-11c7-42f0-ab3e-60f24267026e)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Discord version: Development
 - Any other relevant info: N/A

**Additional context**
N/A

**Comment by wont-stream** [comment]
Adding `transform: scaleX(-1);` to the affected embed images makes it appear normally, but the additional styles would have to be done plugin side so it doesn't apply to every embed image, including non flipped ones.

**Comment by wont-stream** [comment]
I take it back
```css
[class*="_youreRightItem_"] img {
	transform: scaleX(-1);
}
```
seems to fix it

**Comment by wont-stream** [comment]
Of course as I comment I find it affects invites as well
Updated CSS
```css
[class*="_youreRightItem_"] img,
[class*="_youreRightItem_"] [type="button"] [class^="contents_"],
[class*="_youreRightItem_"] [class^="statusCounts_"] {
	transform: scaleX(-1);
}
```
Only somewhat fixes invites

![{207767E6-97EC-47AB-BB78-E8F33481FD2B}](https://github.com/user-attachments/assets/37acb1f6-0e8c-4cb8-b7ea-08c1cfa1bd05)
