### ISSUE TITLE
[Feature Request] You're right, chat cloud styling

### ISSUE THREAD

**Issue by HighPriest** [SpikeHD/shelter-plugins#46]
**Is your feature request related to a problem? Please describe.**
The message size is *complicated*, making text & content wrap in odd places.
Plus, these changes make the UI look more like the Facebook chat clouds

**Describe the solution you'd like**
Swap the CSS a little:

```CSS
.CPnQ-q_youreRightItem [id^="message-content-"] {
    text-align: right;
-   max-width: 60%;
+   padding-left: 0;
}

+yourRightItem
.wrapper.cozy, .wrapper.compact {
     padding: var(--message-padding-top) var(--message-padding-side) !important; 
     padding-right: 8px !important;
     border: 2px solid transparent;
+    max-width: 60%;
+    width: fit-content;
}
```

**Describe alternatives you've considered**
🤷‍♂️

**Additional context**
Before:
![Image](https://github.com/user-attachments/assets/278b9605-55a3-4d35-89af-e9e003bb38ab)

After:
![Image](https://github.com/user-attachments/assets/ae5896b1-ef78-4f57-8900-c8d07383d2be)
